spring:
  datasource:
    url: jdbc:postgresql://shortline.proxy.rlwy.net:23182/railway
    username: postgres
    password: BYEIQTOtydVTJlHsptAfvzrfXgbhDfkI
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



