spring:
  datasource:
    url: jdbc:postgresql://postgres:UzpwBWhJRGTqZQTbAABJBGthSeEBzPhF@turntable.proxy.rlwy.net:18391/railway
    username: postgres
    password: UzpwBWhJRGTqZQTbAABJBGthSeEBzPhF
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: create



